# Site settings
title: Jeff Hilnbrand
email: jahilnbrand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey there, I'm Jeff Hilnbrand. I like making cool things with cool people.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jhil.co" # the base hostname & protocol for your site
permalink: /:title # example: http://jhil.co/bitcamp
twitter_username: jhilmd
github_username:  jhil
timezone: America/New_York

# Build settings
markdown: kramdown